import { Injectable, Inject, NotFoundException, BadRequestException } from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';

import { AuditService } from '../../audit/services/audit.service';
import { ExceptionEntity, ExceptionStatus, ResolutionAction } from '../domain/exception.entity';
import {
  IExceptionRepository,
  EXCEPTION_REPOSITORY_TOKEN,
} from '../domain/exception.repository.interface';
import { CreateExceptionDto, ResolveExceptionDto } from '../dto/exception.dto';

@Injectable()
export class ExceptionService {
  constructor(
    @Inject(EXCEPTION_REPOSITORY_TOKEN)
    private readonly exceptionRepo: IExceptionRepository,
    private readonly auditService: AuditService,
  ) {}

  async createException(tenantId: string, dto: CreateExceptionDto): Promise<ExceptionEntity> {
    const exception: ExceptionEntity = {
      id: uuidv4(),
      tenantId,
      ...dto,
      status: ExceptionStatus.OPEN,
      history: [
        {
          action: 'CREATED',
          timestamp: new Date(),
          actorId: 'SYSTEM', // usually generated by AI/System
        },
      ],
      createdAt: new Date(),
      updatedAt: new Date(),
    };

    const saved = await this.exceptionRepo.create(exception);

    await this.auditService.log({
      tenantId,
      action: 'EXCEPTION_CREATED',
      entityType: 'EXCEPTION',
      entityId: saved.id,
      actorType: 'SYSTEM',
      actorId: 'SYSTEM',
      newState: { type: saved.type, reason: saved.reason },
    });

    return saved;
  }

  async getExceptions(tenantId: string, status?: ExceptionStatus): Promise<ExceptionEntity[]> {
    return this.exceptionRepo.findAll(tenantId, status);
  }

  async resolveException(
    tenantId: string,
    exceptionId: string,
    userId: string,
    dto: ResolveExceptionDto,
  ): Promise<ExceptionEntity> {
    const exception = await this.exceptionRepo.findById(exceptionId, tenantId);
    if (!exception) {
      throw new NotFoundException('Exception not found');
    }

    if (exception.status === ExceptionStatus.RESOLVED) {
      throw new BadRequestException('Exception is already resolved');
    }

    if (!exception.availableActions.includes(dto.action)) {
      throw new BadRequestException(`Action ${dto.action} is not available for this exception.`);
    }

    exception.status =
      dto.action === ResolutionAction.ESCALATE
        ? ExceptionStatus.ESCALATED
        : ExceptionStatus.RESOLVED;
    exception.resolvedAt = new Date();
    exception.resolvedBy = userId;
    exception.resolutionAction = dto.action;
    exception.updatedAt = new Date();

    exception.history.push({
      action: dto.action,
      timestamp: new Date(),
      actorId: userId,
      notes: dto.notes,
    });

    const updated = await this.exceptionRepo.update(exception);

    await this.auditService.log({
      tenantId,
      action: `EXCEPTION_${dto.action}`,
      entityType: 'EXCEPTION',
      entityId: updated.id,
      actorType: 'USER',
      actorId: userId,
      newState: { status: updated.status, action: dto.action, notes: dto.notes },
    });

    return updated;
  }
}
